### ISSUE TITLE
stateSave: true

### ISSUE THREAD

**Issue by mmaglia** [omines/datatables-bundle#179]
Hi. It happens the same to me too. I don't understand why this issue has been closed. I have tried configuring with the `persist_state: "local"` option and in my JS the `stateSave: true` option and every time I reload, the Datatable is initialized as if it were loaded for the first time. I have been able to verify that the local storage is working properly.

_Originally posted by @mmaglia in https://github.com/omines/datatables-bundle/issues/27#issuecomment-677524227_

**Comment by mmaglia** [comment]
Hi. Sorry for not explaining the context. I added the comment that starts this problem in [stateSave: true # 27](https://github.com/omines/datatables-bundle/issues/27#issuecomment-677524227). Then when I saw that it was closed I thought it best to raise as a new problem although I am not sure if it is a problem or a missing functionality or is that I am doing something wrong.

This is my controller
```
    public function index(Request $request): Response
    {

        $table = $this->datatableFactory->createFromType(OficinaTableType::class)->handleRequest($request);
        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('oficina/index.html.twig', ['datatable' => $table]);
    }

```
This is the definition of the TableType
```
`class OficinaTableType extends AbstractController implements DataTableTypeInterface
{
    /**
     * Configuro las columnas y sus funcionamiento de la grilla de oficina
     *
     * @param DataTable $dataTable
     * @return void
     */
    public function configure(DataTable $dataTable)
    {
        // Se agrega la primera columna en blanco para poner el checkbox
        $dataTable->add('', TextColumn::class, ['label' => '']);
        $dataTable->add('id', TextColumn::class, ['label' => '#', 'searchable' => false]);
        $dataTable->add('oficina', TextColumn::class, ['label' => 'Oficina', 'searchable' => true, 'leftExpr' => "toUpper(o.oficina)", 'rightExpr' => function ($value) {
            return '%' . strtoupper($value) . '%';
        }]);
        $dataTable->add('localidad', TextColumn::class, ['label' => 'Localidad', 'searchable' => false,  'field' => 'o.localidad', 'orderField' => 'l.localidad']);

        // Ordenes de la grilla
        $dataTable->addOrderBy('localidad', DataTable::SORT_ASCENDING);
        
        $dataTable->createAdapter(ORMAdapter::class, [
            'entity' => Oficina::class,
            'query' => function (QueryBuilder $builder) {
                $builder
                    ->select('o')
                    ->from(Oficina::class, 'o')
                    ->join('o.localidad', 'l');
            }
        ]);
    }
}
```

This is the JavaScript portion in my view
```
{% block javascripts %}
    {{ parent() }}
    <script>
        $(function() {        
            $(".alert").delay(3500).slideUp(2000);       

            var grillaOficinas = $('#oficinaList').initDataTables( {{ datatable_settings(datatable) }}, {
                searching: true,
                stateSave: true,
            })
        });
    </script>  
    
{% endblock %}   
```

This is my configuration file (datatables.yaml)
```
# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 10
        dom: "B<'row' <'col-sm-6'><'col-sm-6 text-right'f><'col-sm-12' tr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pi>>"

    method: POST
    
    persist_state: "local"

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'

    # Load i18n data from DataTables CDN or locally
    language_from_cdn: true
```

As I said, the page, order, filters, etc. of the DataTable are saved correctly in the local storage. However, when I reload the page, this data is overwritten with the values of a newly initialized DataTable, losing the page, order or filters previously applied.
