### ISSUE TITLE
Filter column not displayed

### ISSUE THREAD

**Issue by FigaCZ** [omines/datatables-bundle#194]
Hello, maybe I didn't search docs deeply, but I am not able to get column filter displayed. I have this setup.

**Controller:**
```
 $userFilter = new ChoiceFilter();
        $userFilter->set([
            'choices' => ['foo' => 'bar', 'bar' => 'baz']
        ]);
        $table = $dataTableFactory->create()
        ->add('created_at', DateTimeColumn::class, ['label' => 'Datum', 'format' => 'j.n.Y H:i', "searchable" => false])
        ->add('userName', TextColumn::class, [
            'label' => 'Uživatel',
            "searchable" => true,
            'render' => function ($value, $context) {
                $user = $context->getUser();

                return $user ? $user->getFirstname().' '.$user->getLastname() : '';
            },
            'filter' => $userFilter
        ])->createAdapter(ORMAdapter::class, [
                'entity' => Copy::class,
            ])
            `->handleRequest($request);
```

**datatables.yaml**

```
# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:
    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 50
        dom: "<'row' <'col-sm-12' ftr>><'row' <'col-sm-6'l><'col-sm-6 text-right'pi>>"
        searching: true

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-striped table-bordered table-hover data-table'
        columnFilter: "both"

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
```

I am not able to see column filter. What is wrong? Setup or datatable template. Thanks for reply.
