### ISSUE TITLE
How can I show a total row?

### ISSUE THREAD

**Issue by lookitsjonno** [omines/datatables-bundle#227]
I would like to add a footer row showing the sum of some columns (for all pages)

Thanks

**Comment by maxhelias** [comment]
You can modify the default options to load into DataTables like that (this is my config with bootstrap 4) : 
```
# config/packages/datatables.yaml
datatables:
    options:
        dom: "<'row' <'col-md-6' B><'col-md-6 ml-md-auto' f>><'row' <'col-md-12 overflow-auto' tr>><'row' <'col-md-6'i><'col-md-6 text-right'p>>"
```
All option is documented here : https://datatables.net/reference/option/dom
